# TODO(fix)
# load("@rules_cc//cc:defs.bzl","cc_test")

# package(default_visibility = ["//visibility:public"])

# cc_test(
#     name = "local_route_test",
#     srcs = ["local_route_test.cc"],
#     deps = [
#         "//apps/planning/src/common:common",
#         "//third_party:googletest"
#     ],
#     linkopts = ["-lpthread","-ldl"],
# )