# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/event.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63ommon/event.proto\x12\x0bzark.common\"\x8e\x01\n\nEventFrame\x12\x12\n\x05stamp\x18\x01 \x01(\x03H\x00\x88\x01\x01\x12\x15\n\x08reporter\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x15\n\x08\x64\x65scribe\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x11\n\x04type\x18\x04 \x01(\rH\x03\x88\x01\x01\x42\x08\n\x06_stampB\x0b\n\t_reporterB\x0b\n\t_describeB\x07\n\x05_typeb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.event_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EVENTFRAME._serialized_start=36
  _EVENTFRAME._serialized_end=178
# @@protoc_insertion_point(module_scope)
