# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/header.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63ommon/header.proto\x12\x0bzark.common\"\x84\x01\n\x06Header\x12\x19\n\x0ctimestamp_ns\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12\x19\n\x0csequence_num\x18\x02 \x01(\x04H\x01\x88\x01\x01\x12\x15\n\x08\x66rame_id\x18\x03 \x01(\x04H\x02\x88\x01\x01\x42\x0f\n\r_timestamp_nsB\x0f\n\r_sequence_numB\x0b\n\t_frame_id\"\xdb\x02\n\x0e\x45xternedHeader\x12/\n\rcommon_header\x18\x01 \x01(\x0b\x32\x13.zark.common.HeaderH\x00\x88\x01\x01\x12\x18\n\x0bmodule_name\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x1c\n\x0flidar_timestamp\x18\x03 \x01(\x04H\x02\x88\x01\x01\x12\x1d\n\x10\x63\x61mera_timestamp\x18\x04 \x01(\x04H\x03\x88\x01\x01\x12\x1c\n\x0fradar_timestamp\x18\x05 \x01(\x04H\x04\x88\x01\x01\x12\x14\n\x07version\x18\x06 \x01(\rH\x05\x88\x01\x01\x12\x15\n\x08\x66rame_id\x18\x07 \x01(\tH\x06\x88\x01\x01\x42\x10\n\x0e_common_headerB\x0e\n\x0c_module_nameB\x12\n\x10_lidar_timestampB\x13\n\x11_camera_timestampB\x12\n\x10_radar_timestampB\n\n\x08_versionB\x0b\n\t_frame_idb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.header_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HEADER._serialized_start=37
  _HEADER._serialized_end=169
  _EXTERNEDHEADER._serialized_start=172
  _EXTERNEDHEADER._serialized_end=519
# @@protoc_insertion_point(module_scope)
