# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/heartbeat.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common import version_pb2 as common_dot_version__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63ommon/heartbeat.proto\x12\x0bzark.common\x1a\x14\x63ommon/version.proto\"\xaf\x01\n\tHeartBeat\x12\x13\n\x0bmodule_name\x18\x01 \x01(\t\x12\x31\n\rmodule_status\x18\x02 \x01(\x0e\x32\x1a.zark.common.MODULE_STATUS\x12*\n\x07version\x18\x03 \x01(\x0b\x32\x19.zark.common.ProtoVersion\x12\x17\n\x0f\x62\x65gin_timestamp\x18\x04 \x01(\x04\x12\x15\n\rend_timestamp\x18\x05 \x01(\x04*\xca\x06\n\rMODULE_STATUS\x12\n\n\x06NORMAL\x10\x00\x12\x17\n\x13\x46RAME_RATE_ABNORMAL\x10\x01\x12\x17\n\x13TIME_STAMP_ABNORMAL\x10\x02\x12\x18\n\x14VISION_DATA_ABNORMAL\x10\x03\x12\x17\n\x13RADAR_DATA_ABNORMAL\x10\x04\x12\x1e\n\x1aLOCALIZATION_DATA_ABNORMAL\x10\x05\x12\x18\n\x14\x46USION_DATA_ABNORMAL\x10\x06\x12\x19\n\x15VEHICLE_DATA_ABNORMAL\x10\x07\x12\x1a\n\x16PLANNING_DATA_ABNORMAL\x10\x08\x12\x1b\n\x17\x46UNCTION_STATE_ABNORMAL\x10\t\x12\x15\n\x11IMU_DATA_ABNORMAL\x10\n\x12 \n\x1cLOCALIZATION_RESULT_ABNORMAL\x10\x0b\x12\x1c\n\x18PERCEPTION_DATA_ABNORMAL\x10\x0c\x12\x1a\n\x16OBSTACLE_DATA_ABNORMAL\x10\r\x12\x17\n\x13HDMAP_DATA_ABNORMAL\x10\x0e\x12 \n\x1cREFERENCE_LINE_DATA_ABNORMAL\x10\x0f\x12\x18\n\x14MODEL_INFER_ABNORMAL\x10\x10\x12\x18\n\x14\x43\x41MERA_DATA_ABNORMAL\x10\x11\x12\x1c\n\x18VISION_TRACKING_ABNORMAL\x10\x12\x12\x1e\n\x1aPERCEPTION_RESULT_ABNORMAL\x10\x13\x12\x1b\n\x17MAPFUSION_DATA_ABNORMAL\x10\x14\x12\x1c\n\x18PREDICTION_DATA_ABNORMAL\x10\x15\x12\x1f\n\x1bMAPENGINE_SDK_INIT_ABNORMAL\x10\x16\x12#\n\x1fMAPENGINE_PROVIDER_SDK_ABNORMAL\x10\x17\x12 \n\x1cMAPENGINE_INPUT_LOC_ABNORMAL\x10\x18\x12\x16\n\x12MAPENGINE_ABNORMAL\x10\x19\x12\x17\n\x13MAPENGINE_INIT_PATH\x10\x1a\x12\x12\n\x0eMAPENGINE_IDLE\x10\x1b\x12\x19\n\x15MODULE_START_ABNORMAL\x10\x64\x12\x17\n\x13MODULE_RUNNING_EXIT\x10\x65\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.heartbeat_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MODULE_STATUS._serialized_start=240
  _MODULE_STATUS._serialized_end=1082
  _HEARTBEAT._serialized_start=62
  _HEARTBEAT._serialized_end=237
# @@protoc_insertion_point(module_scope)
