# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/version.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63ommon/version.proto\x12\x0bzark.common\"t\n\x0cProtoVersion\x12\x1b\n\x0emodule_version\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x1e\n\x11interface_version\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\x11\n\x0f_module_versionB\x14\n\x12_interface_versionb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.version_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PROTOVERSION._serialized_start=37
  _PROTOVERSION._serialized_end=153
# @@protoc_insertion_point(module_scope)
